### ISSUE TITLE
Missing _jobId variable

### ISSUE THREAD

**Issue by rodwayballs** [forcedotcom/postman-salesforce-apis#45]
Hi, the Bulk API collection attempts to set an env variable of `_jobId`, however this isn't present for the collection. I've added it manually and all is well, but it might trip others up.

**Comment by pozil** [comment]
Hi @rodwayballs, thanks for reporting this.
Postman automatically create the `_jobId` variable when it is first assigned so this shouldn't break anything. We decided not to add `_jobId` to the default list of variables in order to keep the list as generic and short as possible. I'll add a note to the documentation about this variable.

**Comment by pozil** [comment]
BTW there are a few other "private" variables like this such as `_batchId` for Bulk API v1. These "private" variables are assigned via scripts running on API responses rather than user-submitted.

**Comment by pozil** [comment]
While documenting the use of the `_jobId` variable, I found issues in the aforementioned scripts. The scripts were reading/writing data from environment variables instead of collection variables.
This is definitely a bug. I fixed it by updating the script. It will now use the environment if available and fall back to collection variables otherwise.

I'll close the issue for now. Let me know if you have other issues.
