### ISSUE TITLE
Collection not updated?

### ISSUE THREAD

**Issue by surajp** [forcedotcom/postman-salesforce-apis#65]
I saw the Salesforce Developer Blog mention that the collection includes an example of the "client_credentials" auth flow. Also, a video for `Event Filtering and Enrichment` was published on the Youtube channel which showcases a folder called "Change Data Capture Custom Channels" . Has this collection not been updated to include those yet?

**Comment by pozil** [comment]
Hi @surajp the collection has indeed been updated with those new features since mid February if I recall well. Make sure to pull the latest version from the [Salesforce Developers Postman public workspace](https://postman.com/salesforce-developers) (this GitHub repository is only used for documentation).

<img width="1247" alt="Screenshot 2023-04-01 at 08 10 41" src="https://user-images.githubusercontent.com/5071767/229269044-49ca2875-a434-4980-8d9e-92e113d91a02.png">
